#!/bin/bash

FNAME=`echo "$1" | sed -e 's/\..*//'`

exitV=`arm-linux-gnueabi-as -o "$FNAME".o "$1"`
if [ $exitV -eq 0 ]; then
  exitV=`arm-linux-gnueabi-ld -o "$FNAME".elf "$FNAME".o`
  if [ $exitV -eq 0 ]; then
    exitV=`arm-linux-gnueabi-objcopy -O binary "$FNAME".elf "$FNAME".bin`
  fi
fi

rm "$FNAME".o "$FNAME".elf

if [ $exitV -eq 0 ]; then
  echo "assembled $1 in $FNAME.bin"
  exit 0
else
  exit $exitV
fi

