#!/bin/bash

FNAME=`echo "$1" | sed -e 's/\..*//'`

arm-linux-gnueabi-as -o "$FNAME".o "$1"
arm-linux-gnueabi-ld -o "$FNAME".elf "$FNAME".o
arm-linux-gnueabi-objcopy -O binary "$FNAME".elf "$FNAME".bin

rm "$FNAME".o "$FNAME".elf

echo "assembled $1 in $FNAME.bin"
