#!/bin/bash

qmake-qt4 >> /dev/null 2> /dev/null
QMAKERET=`echo $?`

if [ $QMAKERET -ne 127 ]; then
  QMCOMP=qmake-qt4
else
  QMCOMP=qmake
  echo "!!!!!!!! it seems you don't have qt4 installed, this may lead to wrong compilation !!!!!!!!"
fi

./configure

$QMCOMP qarm.pro
make
make clean

$QMCOMP elf2uarm.pro
make
make clean

$QMCOMP mkdev.pro
make
make clean
