#!/usr/bin/bash

arm-none-eabi-objdump -d BIOS | sed -e 's/^ 6/ 9/' | sed -e 's/^ 5/ 8/' | sed -e 's/^ 4/ 7/' | sed -e 's/^ 3/ 6/' | sed -e 's/^ 2/ 5/' | sed -e 's/^ 1/ 4/'  | sed -e 's/^   \([0-91-z]\)/ 30\1/' | sed -e 's/^  \([0-9a-z]\)/ 3\1/' | less
